### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by xKryptikzzz** [ProdigyAPI/ProdigyDashboard#3]
I open the file & am brought to a page saying the file was deleted. help?

**Comment by hostedposted** [comment]
Can you screenshot it?

**Comment by xKryptikzzz** [comment]
![image](https://user-images.githubusercontent.com/90012585/132431943-0d6eb5b5-7ebe-4bc2-9de2-e040a1b9805d.png)

**Comment by hostedposted** [comment]
You opened index.html with chrome that's the problem. Use something like [serve](https://www.npmjs.com/package/serve) to serve the project so you can use it.

**Comment by hostedposted** [comment]
Or just use the web version

**Comment by Jps838898** [comment]
web version when i try to log in with my prodigy account it says this 
![Screenshot 2021-09-17 10 12 27](https://user-images.githubusercontent.com/73857889/133827957-183b5129-77ae-43c5-b4d1-86048b81d736.png)
